default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: myapp_user
  password: StrongPass2024!
  host: localhost

development:
  <<: *default
  database: myapp_db

test:
  <<: *default
  database: myapp_db

production:
  <<: *default
  database: myapp_db
  username: myapp_user
  password: StrongPass2024!
